//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuroSoft.DeviceAutoTest.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuroSoft.DeviceAutoTest.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обе.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось включить стимулятор. Устраните проблему и заново запустите тест..
        /// </summary>
        public static string CantEnableStimulator {
            get {
                return ResourceManager.GetString("CantEnableStimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось подключиться к стенду.
        /// </summary>
        public static string CantOpenStand {
            get {
                return ResourceManager.GetString("CantOpenStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите, что к первому USB-порту стенда подключен прибор (при необходимости, подключите)..
        /// </summary>
        public static string ConnectDevice1stPort {
            get {
                return ResourceManager.GetString("ConnectDevice1stPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опишите внесенные исправления:.
        /// </summary>
        public static string CorrectComments {
            get {
                return ResourceManager.GetString("CorrectComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внесение исправлений.
        /// </summary>
        public static string CorrectStr {
            get {
                return ResourceManager.GetString("CorrectStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается открыть устройство.
        /// </summary>
        public static string CouldNotOpenDevice {
            get {
                return ResourceManager.GetString("CouldNotOpenDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка программирования ПЛИС: 
        ///{0}.
        /// </summary>
        public static string CouldNotProgramCpld {
            get {
                return ResourceManager.GetString("CouldNotProgramCpld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить значение размаха.
        /// </summary>
        public static string CouldNotReadSwing {
            get {
                return ResourceManager.GetString("CouldNotReadSwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибор не подключен к 1-му USB-порту стенда.
        /// </summary>
        public static string DeviceNotConnected1stPort {
            get {
                return ResourceManager.GetString("DeviceNotConnected1stPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осциллограф не подключен.
        /// </summary>
        public static string ErrOscScopeNotConnected {
            get {
                return ResourceManager.GetString("ErrOscScopeNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при чтении данных с осциллографа..
        /// </summary>
        public static string ErrOscScopeReadData {
            get {
                return ResourceManager.GetString("ErrOscScopeReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл прошивки не найден.
        /// </summary>
        public static string FirmwareFileDoesNotFound {
            get {
                return ResourceManager.GetString("FirmwareFileDoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Impedance {
            get {
                object obj = ResourceManager.GetObject("Impedance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ток потребления не должен превышать 50 мА. Текущее значение: {0} мА..
        /// </summary>
        public static string InvalidateC123C124Current {
            get {
                return ResourceManager.GetString("InvalidateC123C124Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Левая.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейро-ЭМГ-Микро 2.
        /// </summary>
        public static string NeuroEmgMicro2Name {
            get {
                return ResourceManager.GetString("NeuroEmgMicro2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейро-ЭМГ-Микро 4.
        /// </summary>
        public static string NeuroEmgMicro4Name {
            get {
                return ResourceManager.GetString("NeuroEmgMicro4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейро-ЭМГ-МС.
        /// </summary>
        public static string NeuroEmgMsName {
            get {
                return ResourceManager.GetString("NeuroEmgMsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НейроМВП-Микро (версия 2009).
        /// </summary>
        public static string NeuroMEPMicroMName {
            get {
                return ResourceManager.GetString("NeuroMEPMicroMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НейроМВП-Микро.
        /// </summary>
        public static string NeuroMEPMicroName {
            get {
                return ResourceManager.GetString("NeuroMEPMicroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейрон-Спектр-1...Нейрон-Спектр-4.
        /// </summary>
        public static string NeuronSpectrum1_4Name {
            get {
                return ResourceManager.GetString("NeuronSpectrum1_4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейрон-Спектр-1.
        /// </summary>
        public static string NeuronSpectrum1Name {
            get {
                return ResourceManager.GetString("NeuronSpectrum1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейрон-Спектр-2.
        /// </summary>
        public static string NeuronSpectrum2Name {
            get {
                return ResourceManager.GetString("NeuronSpectrum2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейрон-Спектр-3.
        /// </summary>
        public static string NeuronSpectrum3Name {
            get {
                return ResourceManager.GetString("NeuronSpectrum3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейрон-Спектр-4/ВПМ.
        /// </summary>
        public static string NeuronSpectrum4epmName {
            get {
                return ResourceManager.GetString("NeuronSpectrum4epmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейрон-Спектр-4/ВП.
        /// </summary>
        public static string NeuronSpectrum4epName {
            get {
                return ResourceManager.GetString("NeuronSpectrum4epName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейрон-Спектр-4.
        /// </summary>
        public static string NeuronSpectrum4Name {
            get {
                return ResourceManager.GetString("NeuronSpectrum4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейрон-Спектр-4/П.
        /// </summary>
        public static string NeuronSpectrum4pName {
            get {
                return ResourceManager.GetString("NeuronSpectrum4pName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейрон-Спектр-5.
        /// </summary>
        public static string NeuronSpectrum5Name {
            get {
                return ResourceManager.GetString("NeuronSpectrum5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при открытии файла.
        /// </summary>
        public static string OpenFileError {
            get {
                return ResourceManager.GetString("OpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поли-Спектр-8/EX.
        /// </summary>
        public static string PolySpectrum8exName {
            get {
                return ResourceManager.GetString("PolySpectrum8exName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правая.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программирование ПЛИС успешно завершено..
        /// </summary>
        public static string SuccessProgramCpld {
            get {
                return ResourceManager.GetString("SuccessProgramCpld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка АЧХ прервана пользователем..
        /// </summary>
        public static string TestAFCAborted {
            get {
                return ResourceManager.GetString("TestAFCAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка АЧХ завершена..
        /// </summary>
        public static string TestAFCFinished {
            get {
                return ResourceManager.GetString("TestAFCFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка АЧХ. Частота: {0} Гц. Диапазон: {1:0.#####} В. .
        /// </summary>
        public static string TestAFCStart {
            get {
                return ResourceManager.GetString("TestAFCStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TestDisplayImage {
            get {
                object obj = ResourceManager.GetObject("TestDisplayImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
