//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuroSoft.DeviceAutoTest.OldDevicesTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuroSoft.DeviceAutoTest.OldDevicesTest.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1 слева.
        /// </summary>
        internal static string A1Left {
            get {
                return ResourceManager.GetString("A1Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1 справа.
        /// </summary>
        internal static string A1Right {
            get {
                return ResourceManager.GetString("A1Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует.
        /// </summary>
        internal static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация с модуля АЦП.
        /// </summary>
        internal static string ADCModuleInformation {
            get {
                return ResourceManager.GetString("ADCModuleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код по каналу дыхания.
        /// </summary>
        internal static string BreathChannelCode {
            get {
                return ResourceManager.GetString("BreathChannelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние кнопок или педалей на разъеме XS1.
        /// </summary>
        internal static string ButtonsStateAtXS1 {
            get {
                return ResourceManager.GetString("ButtonsStateAtXS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние кнопок или педалей на разъеме XS2.
        /// </summary>
        internal static string ButtonsStateAtXS2 {
            get {
                return ResourceManager.GetString("ButtonsStateAtXS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значание размаха калибровочного сигнала в канале {0} не соответствует требованиям. Внесите необходимые исправления и выполните тест заново..
        /// </summary>
        internal static string CalibrSignalSwingsInvalid {
            get {
                return ResourceManager.GetString("CalibrSignalSwingsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напряжение сигнала калибровки.
        /// </summary>
        internal static string CalibrVolatage {
            get {
                return ResourceManager.GetString("CalibrVolatage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код тестового сигнала калибровки -.
        /// </summary>
        internal static string CalibrVoltageCodeMinus {
            get {
                return ResourceManager.GetString("CalibrVoltageCodeMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код тестового сигнала калибровки +.
        /// </summary>
        internal static string CalibrVoltageCodePlus {
            get {
                return ResourceManager.GetString("CalibrVoltageCodePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время выполнения проверки распайки разъемов фронтальной панели прибора возникли ошибки. Перезапустите тест и выполните его повторно..
        /// </summary>
        internal static string CheckSocketsErrors {
            get {
                return ResourceManager.GetString("CheckSocketsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключен.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключите электрод.
        /// </summary>
        internal static string ConnectElectrode {
            get {
                return ResourceManager.GetString("ConnectElectrode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключите электрод Ref к {0}-му разъему земли прибора..
        /// </summary>
        internal static string ConnectRefTo {
            get {
                return ResourceManager.GetString("ConnectRefTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код по каналу контроля ответа стимула.
        /// </summary>
        internal static string CurrentStimAnswerCode {
            get {
                return ResourceManager.GetString("CurrentStimAnswerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация с модуля токового стимулятора.
        /// </summary>
        internal static string CurrentStimInformation {
            get {
                return ResourceManager.GetString("CurrentStimInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия модуля токового стимулятора.
        /// </summary>
        internal static string CurrentStimModuleVersion {
            get {
                return ResourceManager.GetString("CurrentStimModuleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код по каналу задания стимула.
        /// </summary>
        internal static string CurrentStimSettingCode {
            get {
                return ResourceManager.GetString("CurrentStimSettingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напряжение на канале DC1.
        /// </summary>
        internal static string DC1Voltage {
            get {
                return ResourceManager.GetString("DC1Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напряжение на канале DC2.
        /// </summary>
        internal static string DC2Voltage {
            get {
                return ResourceManager.GetString("DC2Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное наименование прибора.
        /// </summary>
        internal static string DeviceFullName {
            get {
                return ResourceManager.GetString("DeviceFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя устройства.
        /// </summary>
        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серийный номер прибора.
        /// </summary>
        internal static string DeviceSerialNumber {
            get {
                return ResourceManager.GetString("DeviceSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип прибора.
        /// </summary>
        internal static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия прибора.
        /// </summary>
        internal static string DeviceVersion {
            get {
                return ResourceManager.GetString("DeviceVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЭКГ.
        /// </summary>
        internal static string ECG {
            get {
                return ResourceManager.GetString("ECG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип усилителей в каналах ЭЭГ.
        /// </summary>
        internal static string EEGAmplifiersType {
            get {
                return ResourceManager.GetString("EEGAmplifiersType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электрод.
        /// </summary>
        internal static string Electrode {
            get {
                return ResourceManager.GetString("Electrode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение сопротивления {0} не соответствует требованию. Внесите исправления и выполните тест заново..
        /// </summary>
        internal static string ElectrodeImpInvalidMessage {
            get {
                return ResourceManager.GetString("ElectrodeImpInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение напряжения поляризации электрода {0} отличается от напряжения поляризации других электродов более чем на 2 мВ. Внесите необходимые исправления и выполните тест заново..
        /// </summary>
        internal static string ElectrodePolarDiffInvalidMessage {
            get {
                return ResourceManager.GetString("ElectrodePolarDiffInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение напряжения поляризации {0} не соответствует требованию. Внесите исправления и выполните тест заново..
        /// </summary>
        internal static string ElectrodePolarisationInvalidMessage {
            get {
                return ResourceManager.GetString("ElectrodePolarisationInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} к разъему земли прибора..
        /// </summary>
        internal static string ElectrodeToDeviceGnd {
            get {
                return ResourceManager.GetString("ElectrodeToDeviceGnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезапуск процессора по неизвестной причине.
        /// </summary>
        internal static string ErrorProcRestart {
            get {
                return ResourceManager.GetString("ErrorProcRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переполнение стека.
        /// </summary>
        internal static string ErrorStackOverFlow {
            get {
                return ResourceManager.GetString("ErrorStackOverFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует сигнал от источника питания.
        /// </summary>
        internal static string ErrorSupplyAbsent {
            get {
                return ResourceManager.GetString("ErrorSupplyAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в тесте регистров ключей.
        /// </summary>
        internal static string ErrorSwitchesTest {
            get {
                return ResourceManager.GetString("ErrorSwitchesTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия встроенного ПО.
        /// </summary>
        internal static string FirmwareVersion {
            get {
                return ResourceManager.GetString("FirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ориентация головы на панели прибора.
        /// </summary>
        internal static string FrontPanelHeadOrientation {
            get {
                return ResourceManager.GetString("FrontPanelHeadOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Земля.
        /// </summary>
        internal static string GND {
            get {
                return ResourceManager.GetString("GND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код нуля.
        /// </summary>
        internal static string GndChannelCode {
            get {
                return ResourceManager.GetString("GndChannelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код по каналу контроля высокого напряжения.
        /// </summary>
        internal static string HighVoltControlChannelCode {
            get {
                return ResourceManager.GetString("HighVoltControlChannelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напряжение сигнала измерения импеанса.
        /// </summary>
        internal static string ImpedanceMeasureVoltage {
            get {
                return ResourceManager.GetString("ImpedanceMeasureVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сопротивление электрода {0} составляет {1} кОм.
        /// </summary>
        internal static string ImpedanceOfIs {
            get {
                return ResourceManager.GetString("ImpedanceOfIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация с процессора USB.
        /// </summary>
        internal static string InfomationFromUSBProc {
            get {
                return ResourceManager.GetString("InfomationFromUSBProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размах сигнала в канале {0} на диапазоне {1} не соответствует требуемому значению {2}. Внесите необходимые исправления и выполните тест заново..
        /// </summary>
        internal static string InputRagesTestInvalidMessage {
            get {
                return ResourceManager.GetString("InputRagesTestInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия модуля индикации и клавиатуры.
        /// </summary>
        internal static string KeyIndicationModuleVersion {
            get {
                return ResourceManager.GetString("KeyIndicationModuleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние кнопок модуля клавиатуры.
        /// </summary>
        internal static string KeyModuleButtonsState {
            get {
                return ResourceManager.GetString("KeyModuleButtonsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о модуле клавиатуры.
        /// </summary>
        internal static string KeyModuleInformation {
            get {
                return ResourceManager.GetString("KeyModuleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия модуля клавиатуры.
        /// </summary>
        internal static string KeyModuleVersion {
            get {
                return ResourceManager.GetString("KeyModuleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество ключей.
        /// </summary>
        internal static string KeysNumber {
            get {
                return ResourceManager.GetString("KeysNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мА.
        /// </summary>
        internal static string mA {
            get {
                return ResourceManager.GetString("mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неисправность в устройстве.
        /// </summary>
        internal static string MalfunctionInDevice {
            get {
                return ResourceManager.GetString("MalfunctionInDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мкВ.
        /// </summary>
        internal static string mkV {
            get {
                return ResourceManager.GetString("mkV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение многоканального коммутатора токового стимулятора.
        /// </summary>
        internal static string MultiChanCurrentStimIsConnected {
            get {
                return ResourceManager.GetString("MultiChanCurrentStimIsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мВ.
        /// </summary>
        internal static string mV {
            get {
                return ResourceManager.GetString("mV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значание размаха сигнала {0} в канале {1} не соответствует требованиям. Внесите необходимые исправления и выполните тест заново..
        /// </summary>
        internal static string NoiseSwingsInvalidMessage {
            get {
                return ResourceManager.GetString("NoiseSwingsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не подключен.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не нажата.
        /// </summary>
        internal static string NotPushed {
            get {
                return ResourceManager.GetString("NotPushed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхроимпульсы не зафиксированы. Устраните неисправность и выполните тест заново..
        /// </summary>
        internal static string NotSynchroImpulse {
            get {
                return ResourceManager.GetString("NotSynchroImpulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OfNoise {
            get {
                return ResourceManager.GetString("OfNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение паттерна.
        /// </summary>
        internal static string PatternConnection {
            get {
                return ResourceManager.GetString("PatternConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адаптер шахматного паттерна не подключен к устройству..
        /// </summary>
        internal static string PatternNotConnected {
            get {
                return ResourceManager.GetString("PatternNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация с модуля фото-фоностимулятора.
        /// </summary>
        internal static string PhotoPhonoModuleInformation {
            get {
                return ResourceManager.GetString("PhotoPhonoModuleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия фото-фоно стимулятора.
        /// </summary>
        internal static string PhotoPhonoStimVersion {
            get {
                return ResourceManager.GetString("PhotoPhonoStimVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время проверки обмена возникли ошибки!.
        /// </summary>
        internal static string PilaTestErrMsg {
            get {
                return ResourceManager.GetString("PilaTestErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о нажатии кнопки.
        /// </summary>
        internal static string PushButtonInformation {
            get {
                return ResourceManager.GetString("PushButtonInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажата.
        /// </summary>
        internal static string Pushed {
            get {
                return ResourceManager.GetString("Pushed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опорное напряжение.
        /// </summary>
        internal static string ReferenceVoltage {
            get {
                return ResourceManager.GetString("ReferenceVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код опорного напряжения +2,5В.
        /// </summary>
        internal static string RefVoltageCode {
            get {
                return ResourceManager.GetString("RefVoltageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код перезапуска.
        /// </summary>
        internal static string RestartCode {
            get {
                return ResourceManager.GetString("RestartCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ы.
        /// </summary>
        internal static string S_PluralEnd {
            get {
                return ResourceManager.GetString("S_PluralEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установлен.
        /// </summary>
        internal static string Setted {
            get {
                return ResourceManager.GetString("Setted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличие модуля SpO2.
        /// </summary>
        internal static string SpO2Availability {
            get {
                return ResourceManager.GetString("SpO2Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация с модуля SpO2.
        /// </summary>
        internal static string SpO2ModuleInformation {
            get {
                return ResourceManager.GetString("SpO2ModuleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о модуле стимулятора.
        /// </summary>
        internal static string StimModuleInformation {
            get {
                return ResourceManager.GetString("StimModuleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to успешно.
        /// </summary>
        internal static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестирование завершено.
        /// </summary>
        internal static string TestingFinished {
            get {
                return ResourceManager.GetString("TestingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестирование не было завершено. Выполните тест полностью..
        /// </summary>
        internal static string TestingNotFinished {
            get {
                return ResourceManager.GetString("TestingNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка к тестированию....
        /// </summary>
        internal static string TestPreparing {
            get {
                return ResourceManager.GetString("TestPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код тестового сигнала измерения импеданса -.
        /// </summary>
        internal static string TestVoltageCodeMinus {
            get {
                return ResourceManager.GetString("TestVoltageCodeMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код тестового сигнала измерения импеданса +.
        /// </summary>
        internal static string TestVoltageCodePlus {
            get {
                return ResourceManager.GetString("TestVoltageCodePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка принудительно остановлена..
        /// </summary>
        internal static string TestWasStoppedForcibly {
            get {
                return ResourceManager.GetString("TestWasStoppedForcibly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация с модуля потоков.
        /// </summary>
        internal static string ThreadModuleInformation {
            get {
                return ResourceManager.GetString("ThreadModuleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия модуля потоков.
        /// </summary>
        internal static string ThreadModuleVersion {
            get {
                return ResourceManager.GetString("ThreadModuleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалсоь получить результаты проверки распайки разъемов фронтальной панели прибора. Перезапустите тест и выполните его повторно..
        /// </summary>
        internal static string UnableGetCheckSocketsResult {
            get {
                return ResourceManager.GetString("UnableGetCheckSocketsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно получить контрол чтения данных.
        /// </summary>
        internal static string UnableGetReadDataControl {
            get {
                return ResourceManager.GetString("UnableGetReadDataControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить значения размахов сигнала..
        /// </summary>
        internal static string UnableGetSwingsValues {
            get {
                return ResourceManager.GetString("UnableGetSwingsValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия встроенного ПО процессора USB.
        /// </summary>
        internal static string USBProcFirmwareVersion {
            get {
                return ResourceManager.GetString("USBProcFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия процессора USB.
        /// </summary>
        internal static string USBProcVersion {
            get {
                return ResourceManager.GetString("USBProcVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В.
        /// </summary>
        internal static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код по каналу контроля напряжения.
        /// </summary>
        internal static string VoltageControlChannelCode {
            get {
                return ResourceManager.GetString("VoltageControlChannelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to с ошибками.
        /// </summary>
        internal static string WithMistakes {
            get {
                return ResourceManager.GetString("WithMistakes", resourceCulture);
            }
        }
    }
}
