//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuroSoft.DeviceAutoTest.OldDevicesTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuroSoft.DeviceAutoTest.OldDevicesTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось подключиться к стенду.
        /// </summary>
        internal static string CantOpenStand {
            get {
                return ResourceManager.GetString("CantOpenStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка!.
        /// </summary>
        internal static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка индикации проведена неполностью. Произведите все требуемые действия и выполните тест заново..
        /// </summary>
        internal static string IndicationErrorString {
            get {
                return ResourceManager.GetString("IndicationErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ходе проверки клавиатуры были нажаты не все кнопки. Проверьте все кнопки и заново выполните тест..
        /// </summary>
        internal static string KeyBoardErrorString {
            get {
                return ResourceManager.GetString("KeyBoardErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка входного диапазона. Размах {0}. Диапазон: {1}.
        /// </summary>
        internal static string TestInputRangeStart {
            get {
                return ResourceManager.GetString("TestInputRangeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка входного диапазона завершена {0}..
        /// </summary>
        internal static string TestInputRangeStop {
            get {
                return ResourceManager.GetString("TestInputRangeStop", resourceCulture);
            }
        }
    }
}
