//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuroSoft.DeviceAutoTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuroSoft.DeviceAutoTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина:.
        /// </summary>
        public static string AbortReason {
            get {
                return ResourceManager.GetString("AbortReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена результатов действия.
        /// </summary>
        public static string AbortStr {
            get {
                return ResourceManager.GetString("AbortStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutFormAppVersionEng {
            get {
                return ResourceManager.GetString("AboutFormAppVersionEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия:.
        /// </summary>
        public static string AboutFormAppVersionRu {
            get {
                return ResourceManager.GetString("AboutFormAppVersionRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version / Версия:.
        /// </summary>
        public static string AboutFormAppVersionUni {
            get {
                return ResourceManager.GetString("AboutFormAppVersionUni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date:.
        /// </summary>
        public static string AboutFormReleaseDateEng {
            get {
                return ResourceManager.GetString("AboutFormReleaseDateEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата релиза:.
        /// </summary>
        public static string AboutFormReleaseDateRu {
            get {
                return ResourceManager.GetString("AboutFormReleaseDateRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date / Дата релиза:.
        /// </summary>
        public static string AboutFormReleaseDateUni {
            get {
                return ResourceManager.GetString("AboutFormReleaseDateUni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported devices:.
        /// </summary>
        public static string AboutFormSuppDevsEng {
            get {
                return ResourceManager.GetString("AboutFormSuppDevsEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддерживаемые устройства:.
        /// </summary>
        public static string AboutFormSuppDevsRu {
            get {
                return ResourceManager.GetString("AboutFormSuppDevsRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported devices / Поддерживаемые устройства:.
        /// </summary>
        public static string AboutFormSuppDevsUni {
            get {
                return ResourceManager.GetString("AboutFormSuppDevsUni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS:.
        /// </summary>
        public static string AboutFormSuppOsEng {
            get {
                return ResourceManager.GetString("AboutFormSuppOsEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОС:.
        /// </summary>
        public static string AboutFormSuppOsRu {
            get {
                return ResourceManager.GetString("AboutFormSuppOsRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS / ОС:.
        /// </summary>
        public static string AboutFormSuppOsUni {
            get {
                return ResourceManager.GetString("AboutFormSuppOsUni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматическое тестирование завершено..
        /// </summary>
        public static string atComplete {
            get {
                return ResourceManager.GetString("atComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматическое тестирование завершено.
        ///Тестов запущено: {0} из {1}
        ///Пропущено: {2} из {0}
        ///Выполнено: {3} из {0}.
        /// </summary>
        public static string atCompleteFull {
            get {
                return ResourceManager.GetString("atCompleteFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершение теста &apos;{0}&apos;....
        /// </summary>
        public static string atExecuteTest {
            get {
                return ResourceManager.GetString("atExecuteTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение теста в РУЧНОМ РЕЖИМЕ: &apos;{0}&apos;.
        /// </summary>
        public static string atManualTest {
            get {
                return ResourceManager.GetString("atManualTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск теста &apos;{0}&apos;....
        /// </summary>
        public static string atStartTest {
            get {
                return ResourceManager.GetString("atStartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматическое тестирование остановлено..
        /// </summary>
        public static string atStopped {
            get {
                return ResourceManager.GetString("atStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение теста &apos;{0}&apos;....
        /// </summary>
        public static string atWaitTest {
            get {
                return ResourceManager.GetString("atWaitTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BackGr {
            get {
                object obj = ResourceManager.GetObject("BackGr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close_1_english {
            get {
                object obj = ResourceManager.GetObject("close_1_english", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close_1_russian {
            get {
                object obj = ResourceManager.GetObject("close_1_russian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close_2_english {
            get {
                object obj = ResourceManager.GetObject("close_2_english", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close_2_russian {
            get {
                object obj = ResourceManager.GetObject("close_2_russian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить наладку.
        /// </summary>
        public static string CloseTesting {
            get {
                return ResourceManager.GetString("CloseTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие.
        /// </summary>
        public static string CommonPPMBlocks {
            get {
                return ResourceManager.GetString("CommonPPMBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция завершена.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить {0} тестов?.
        /// </summary>
        public static string ConfirmDeleteTests {
            get {
                return ResourceManager.GetString("ConfirmDeleteTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите перезаписать инструкцию &apos;{0}&apos; версии &apos;{1}&apos; в базе данных &apos;{2}&apos;?.
        /// </summary>
        public static string ConfirmExportToDB {
            get {
                return ResourceManager.GetString("ConfirmExportToDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите игнорировать состояния тестов, выполнение которых необходимо для прохождения данного теста?.
        /// </summary>
        public static string ConfirmIgnoreTestDependencies {
            get {
                return ResourceManager.GetString("ConfirmIgnoreTestDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите импортировать тест &apos;{0}&apos; из инструкции по наладке &apos;{1}&apos;? В результате обновления теста текущие данные теста будут потеряны..
        /// </summary>
        public static string ConfirmImportTest {
            get {
                return ResourceManager.GetString("ConfirmImportTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите увеличить версию инструкции &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmIncreaseTemplateVersion {
            get {
                return ResourceManager.GetString("ConfirmIncreaseTemplateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция с таким идентификатором уже существует. Удалить существующую инструкцию?.
        /// </summary>
        public static string ConfirmOverwriteTemplateByImport {
            get {
                return ResourceManager.GetString("ConfirmOverwriteTemplateByImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить инструкцию по наладке &quot;{0}&quot;?.
        /// </summary>
        public static string ConfirmRemoveDATTemplate {
            get {
                return ResourceManager.GetString("ConfirmRemoveDATTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить папку &apos;{0}&apos; со всем её содержимым?.
        /// </summary>
        public static string ConfirmRemoveFolder {
            get {
                return ResourceManager.GetString("ConfirmRemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены,что хотите удалить скрипт &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmRemoveScript {
            get {
                return ResourceManager.GetString("ConfirmRemoveScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить тест &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmRemoveTest {
            get {
                return ResourceManager.GetString("ConfirmRemoveTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены,что хотите удалить группу тестов &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmRemoveTestGroup {
            get {
                return ResourceManager.GetString("ConfirmRemoveTestGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвержение завершения теста.
        /// </summary>
        public static string ConfirmTestFinishing {
            get {
                return ResourceManager.GetString("ConfirmTestFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание всех исправлений и отклонений..
        /// </summary>
        public static string CorrectionsAndErrorsTagDescription {
            get {
                return ResourceManager.GetString("CorrectionsAndErrorsTagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имена тестов с исправлениями или отклонениями.
        /// </summary>
        public static string CorrectionsAndErrorsTestNamesTagDescription {
            get {
                return ResourceManager.GetString("CorrectionsAndErrorsTestNamesTagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить класс {0}.
        /// </summary>
        public static string CouldNotLoadClass {
            get {
                return ResourceManager.GetString("CouldNotLoadClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая дата.
        /// </summary>
        public static string CurrentDateTagDescription {
            get {
                return ResourceManager.GetString("CurrentDateTagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цикл.
        /// </summary>
        public static string CycleBlock {
            get {
                return ResourceManager.GetString("CycleBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceAutoTest Template Archieve (*.dattmp) | *.dattmp.
        /// </summary>
        public static string DATTemplateFilter {
            get {
                return ResourceManager.GetString("DATTemplateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнить.
        /// </summary>
        public static string DefaultButtonScriptDescription {
            get {
                return ResourceManager.GetString("DefaultButtonScriptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string DefaultButtonScriptName {
            get {
                return ResourceManager.GetString("DefaultButtonScriptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на содержимое.
        /// </summary>
        public static string DefaultContentPresenterTagDescription {
            get {
                return ResourceManager.GetString("DefaultContentPresenterTagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая папка.
        /// </summary>
        public static string DefaultFolderName {
            get {
                return ResourceManager.GetString("DefaultFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание скрипта.
        /// </summary>
        public static string DefaultScriptDescription {
            get {
                return ResourceManager.GetString("DefaultScriptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая инструкция по наладке.
        /// </summary>
        public static string DefaultTemplateName {
            get {
                return ResourceManager.GetString("DefaultTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание внесенного исправления.
        /// </summary>
        public static string DefaultTestCorrectionStr {
            get {
                return ResourceManager.GetString("DefaultTestCorrectionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа тестов.
        /// </summary>
        public static string DefaultTestGroupName {
            get {
                return ResourceManager.GetString("DefaultTestGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый тест.
        /// </summary>
        public static string DefaultTestItemName {
            get {
                return ResourceManager.GetString("DefaultTestItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переменная.
        /// </summary>
        public static string DefaultVariableDescription {
            get {
                return ResourceManager.GetString("DefaultVariableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серийный номер устройства.
        /// </summary>
        public static string DeviceSNTagDescription {
            get {
                return ResourceManager.GetString("DeviceSNTagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переменная окружения.
        /// </summary>
        public static string EnvironmentTagDescription {
            get {
                return ResourceManager.GetString("EnvironmentTagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если...То.
        /// </summary>
        public static string IfThenElseBlock {
            get {
                return ResourceManager.GetString("IfThenElseBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальный снимок.
        /// </summary>
        public static string InitialSnapshot {
            get {
                return ResourceManager.GetString("InitialSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимый идентификатор.
        /// </summary>
        public static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимое имя скрипта.
        /// </summary>
        public static string InvalidScriptName {
            get {
                return ResourceManager.GetString("InvalidScriptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление теста с таким идентификатором влечет к созданию переменной, имя которой занято: {0}.
        /// </summary>
        public static string InvalidTestIdVariableExitsts {
            get {
                return ResourceManager.GetString("InvalidTestIdVariableExitsts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимое имя переменной.
        /// </summary>
        public static string InvalidVariableName {
            get {
                return ResourceManager.GetString("InvalidVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить инструкцию по наладке: {0}.
        /// </summary>
        public static string LoadTemplateError {
            get {
                return ResourceManager.GetString("LoadTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не все необходимые тесты выполнены..
        /// </summary>
        public static string NeedToExecuteTests {
            get {
                return ResourceManager.GetString("NeedToExecuteTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать наладку устройства....
        /// </summary>
        public static string NewTesting {
            get {
                return ResourceManager.GetString("NewTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать наладку нового устройства....
        /// </summary>
        public static string NewTestingTooltip {
            get {
                return ResourceManager.GetString("NewTestingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любое.
        /// </summary>
        public static string NoDeviceTypeFilter {
            get {
                return ResourceManager.GetString("NoDeviceTypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Nsft {
            get {
                object obj = ResourceManager.GetObject("Nsft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Nsft_ru {
            get {
                object obj = ResourceManager.GetObject("Nsft_ru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данная операция доступна только администратору системы.
        /// </summary>
        public static string OnlyAdminError {
            get {
                return ResourceManager.GetString("OnlyAdminError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OscScopeControlSettings.
        /// </summary>
        public static string OscScopeControlSettings {
            get {
                return ResourceManager.GetString("OscScopeControlSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pctgrm {
            get {
                object obj = ResourceManager.GetObject("Pctgrm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В базе данных уже существует инструкция &apos;{0}&apos; версии {1}. Перезаписать существующую инструкцию?.
        /// </summary>
        public static string ReplaceExistingTemplate {
            get {
                return ResourceManager.GetString("ReplaceExistingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторное прохождение теста.
        /// </summary>
        public static string ReTestComment {
            get {
                return ResourceManager.GetString("ReTestComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция по наладке была изменена, сохранить изменения?.
        /// </summary>
        public static string SaveModifiedTemplate {
            get {
                return ResourceManager.GetString("SaveModifiedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить результаты наладки.
        /// </summary>
        public static string SaveTesting {
            get {
                return ResourceManager.GetString("SaveTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В результате выполнения скрипта произошла ошибка:
        ///{0}.
        /// </summary>
        public static string ScriptExecutionError {
            get {
                return ResourceManager.GetString("ScriptExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрипт с таким идентификатором уже существует.
        /// </summary>
        public static string ScriptNameExists {
            get {
                return ResourceManager.GetString("ScriptNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор скрипта не может быть пустым.
        /// </summary>
        public static string ScriptNameMustBeNotEmpty {
            get {
                return ResourceManager.GetString("ScriptNameMustBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для данного устройства уже существует процесс наладки..
        /// </summary>
        public static string SerialNumberAlreadyExists {
            get {
                return ResourceManager.GetString("SerialNumberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серийный номер не может быть пустым.
        /// </summary>
        public static string SerialNumberMustBeNotEmpty {
            get {
                return ResourceManager.GetString("SerialNumberMustBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приступить к наладке....
        /// </summary>
        public static string StartTestingText {
            get {
                return ResourceManager.GetString("StartTestingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приступить к процессу наладки устройства....
        /// </summary>
        public static string StartTestingToolTip {
            get {
                return ResourceManager.GetString("StartTestingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индикатор тока потребления.
        /// </summary>
        public static string SupplyCurrentTag {
            get {
                return ResourceManager.GetString("SupplyCurrentTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тег с таким идентификатором уже существует.
        /// </summary>
        public static string TagAlreadyExists {
            get {
                return ResourceManager.GetString("TagAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти подходяющую инструкцию для импорта.
        /// </summary>
        public static string TemplateForImportDoesNotFound {
            get {
                return ResourceManager.GetString("TemplateForImportDoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти шаблон теста для импорта.
        /// </summary>
        public static string TemplateItemForImportDoesNotFound {
            get {
                return ResourceManager.GetString("TemplateItemForImportDoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция по наладке с таким именем уже существует.
        /// </summary>
        public static string TemplateNameExists {
            get {
                return ResourceManager.GetString("TemplateNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя инструкции по наладке не может быть пустым.
        /// </summary>
        public static string TemplateNameMustBeNotEmpty {
            get {
                return ResourceManager.GetString("TemplateNameMustBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данная инструкция не найдена.
        /// </summary>
        public static string TemplateNotFound {
            get {
                return ResourceManager.GetString("TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия инструкции по наладке.
        /// </summary>
        public static string TemplateVersionTagDescription {
            get {
                return ResourceManager.GetString("TemplateVersionTagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест успешно выполнен..
        /// </summary>
        public static string TestExecutedSuccessfully {
            get {
                return ResourceManager.GetString("TestExecutedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест выполнен с исправлениями..
        /// </summary>
        public static string TestExecutedWithCorrections {
            get {
                return ResourceManager.GetString("TestExecutedWithCorrections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест выполнен с ошибками..
        /// </summary>
        public static string TestExecutedWithErrors {
            get {
                return ResourceManager.GetString("TestExecutedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест &apos;{0}&apos; выполнен c отрицательным результатом..
        /// </summary>
        public static string TestFailed {
            get {
                return ResourceManager.GetString("TestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал действий.
        /// </summary>
        public static string TestHistoryStr {
            get {
                return ResourceManager.GetString("TestHistoryStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест с таким идентификатором уже существует.
        /// </summary>
        public static string TestIdExists {
            get {
                return ResourceManager.GetString("TestIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор теста должен начинаться с латинской буквы и содержать только латинские буквы, цифры и знак подчеркивания..
        /// </summary>
        public static string TestIdLimitations {
            get {
                return ResourceManager.GetString("TestIdLimitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор теста не может быть пустым.
        /// </summary>
        public static string TestIdMustBeNotEmpty {
            get {
                return ResourceManager.GetString("TestIdMustBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наладка.
        /// </summary>
        public static string TestingCheckupGroupName {
            get {
                return ResourceManager.GetString("TestingCheckupGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты теста &apos;{0}&apos; отменены..
        /// </summary>
        public static string TestIsAborted {
            get {
                return ResourceManager.GetString("TestIsAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идет загрузка теста....
        /// </summary>
        public static string TestIsNotLoaded {
            get {
                return ResourceManager.GetString("TestIsNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наладка устройства (v. {0}).
        /// </summary>
        public static string TestsTreeObjectHeader {
            get {
                return ResourceManager.GetString("TestsTreeObjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест &apos;{0}&apos; успешно выполнен.
        /// </summary>
        public static string TestSuccess {
            get {
                return ResourceManager.GetString("TestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт теста успешно завершен.
        /// </summary>
        public static string TestSuccessfullyImported {
            get {
                return ResourceManager.GetString("TestSuccessfullyImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция &apos;{0}&apos; версии {1} успешно изменена. Для фиксации изменений сохраните обследование..
        /// </summary>
        public static string TestTemplateWasUpdated {
            get {
                return ResourceManager.GetString("TestTemplateWasUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произведено исправление.
        /// </summary>
        public static string TestWasCorrected {
            get {
                return ResourceManager.GetString("TestWasCorrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsbDevsListControlSettings.
        /// </summary>
        public static string UsbDevsListControlSettings {
            get {
                return ResourceManager.GetString("UsbDevsListControlSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валидация прервана.
        /// </summary>
        public static string ValidationCanceled {
            get {
                return ResourceManager.GetString("ValidationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при выполнении валидации.
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валидация завершена.
        /// </summary>
        public static string ValidationFinished {
            get {
                return ResourceManager.GetString("ValidationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест: {0}. Скрипт: {1}..
        /// </summary>
        public static string ValidationScriptProgressMsg {
            get {
                return ResourceManager.GetString("ValidationScriptProgressMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такое значение уже существует.
        /// </summary>
        public static string ValueAlreadyExists {
            get {
                return ResourceManager.GetString("ValueAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не должно быть пустым.
        /// </summary>
        public static string ValueMustBeNotEmpty {
            get {
                return ResourceManager.GetString("ValueMustBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переменная с таким именем уже существует..
        /// </summary>
        public static string VariableAlreadyExists {
            get {
                return ResourceManager.GetString("VariableAlreadyExists", resourceCulture);
            }
        }
    }
}
