//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuroSoft.DeviceAutoTest.NewDevicesTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuroSoft.DeviceAutoTest.NewDevicesTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обе.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось подключиться к стенду.
        /// </summary>
        public static string CantOpenStand {
            get {
                return ResourceManager.GetString("CantOpenStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите, что к первому USB-порту стенда подключен прибор (при необходимости, подключите)..
        /// </summary>
        public static string ConnectDevice1stPort {
            get {
                return ResourceManager.GetString("ConnectDevice1stPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опишите внесенные исправления:.
        /// </summary>
        public static string CorrectComments {
            get {
                return ResourceManager.GetString("CorrectComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внесение исправлений.
        /// </summary>
        public static string CorrectStr {
            get {
                return ResourceManager.GetString("CorrectStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается открыть устройство.
        /// </summary>
        public static string CouldNotOpenDevice {
            get {
                return ResourceManager.GetString("CouldNotOpenDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка программирования ПЛИС: 
        ///{0}.
        /// </summary>
        public static string CouldNotProgramCpld {
            get {
                return ResourceManager.GetString("CouldNotProgramCpld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить значение размаха.
        /// </summary>
        public static string CouldNotReadSwing {
            get {
                return ResourceManager.GetString("CouldNotReadSwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибор не подключен к 1-му USB-порту стенда.
        /// </summary>
        public static string DeviceNotConnected1stPort {
            get {
                return ResourceManager.GetString("DeviceNotConnected1stPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки яркости и контрастности дисплея не сохранены..
        /// </summary>
        public static string DisplaySettingsNotSaved {
            get {
                return ResourceManager.GetString("DisplaySettingsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл прошивки не найден.
        /// </summary>
        public static string FirmwareFileDoesNotFound {
            get {
                return ResourceManager.GetString("FirmwareFileDoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ток потребления не должен превышать 50 мА. Текущее значение: {0} мА..
        /// </summary>
        public static string InvalidateC123C124Current {
            get {
                return ResourceManager.GetString("InvalidateC123C124Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Левая.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо включить фотостимулятор при проверке уровня шума!.
        /// </summary>
        public static string NoiseTestWithoutFotoStimErrMsg {
            get {
                return ResourceManager.GetString("NoiseTestWithoutFotoStimErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не все необходимые проверки были выполнены..
        /// </summary>
        public static string NotAllDisplayCheckMade {
            get {
                return ResourceManager.GetString("NotAllDisplayCheckMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при открытии файла.
        /// </summary>
        public static string OpenFileError {
            get {
                return ResourceManager.GetString("OpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правая.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программирование ПЛИС успешно завершено..
        /// </summary>
        public static string SuccessProgramCpld {
            get {
                return ResourceManager.GetString("SuccessProgramCpld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхроимпульсы стимулятора не были зафиксированы..
        /// </summary>
        public static string SyncStimsNotCaptured {
            get {
                return ResourceManager.GetString("SyncStimsNotCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка АЧХ прервана пользователем..
        /// </summary>
        public static string TestAFCAborted {
            get {
                return ResourceManager.GetString("TestAFCAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка АЧХ завершена..
        /// </summary>
        public static string TestAFCFinished {
            get {
                return ResourceManager.GetString("TestAFCFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка АЧХ. Частота: {0} Гц. Диапазон: {1:0.#####} В. .
        /// </summary>
        public static string TestAFCStart {
            get {
                return ResourceManager.GetString("TestAFCStart", resourceCulture);
            }
        }
    }
}
